@LinkShortener_HostAddress = https://localhost:7038

### Create a link
POST {{LinkShortener_HostAddress}}/api/links
Content-Type: application/json

{
  "originalUrl": "https://learn.microsoft.com/en-us/aspnet/core"
}

### Fail example (Error: 400)
POST {{LinkShortener_HostAddress}}/api/links
Content-Type: application/json

{
  "originalUrl": "not-a-url"
}

### Follow a slug (replace the slug with a real one from the 'Create a link' above)
GET {{LinkShortener_HostAddress}}/PtAy4BA

### Unknown slug (Error: 404)
GET {{LinkShortener_HostAddress}}/nope123
